# TODO: Document (class level)

class ConfigConstants:
    BORDER = "border"
    CATEGORIES = "categories"
    DL_DIR = "dl_dir"
    DOWNLOAD = "download"
    DOWNLOADS = "downloads"
    EXTENSIONS = "extensions"
    GENERAL = "general"
    FAVORITES = "favorites"
    FLAGS = "flags"
    HEIGHT = "height"
    IMAGE = "image"
    INVENTORY = "inventory"
    PARSERS = "parsers"
    QUERY = "query"
    RATIO = "ratio"
    RECORDS = "records"
    TEXT = "text"
    TEST = "test"
    UI = "ui"
    VIEW = "view"
    WIDTH = "width"
    WRITE_EVERY = "write_every"
