class ConfigConstants:
    CATEGORIES = "categories"
    DL_DIR = "dl_dir"
    GENERAL = "general"
    DOWNLOAD = "download"
    DOWNLOADS = "downloads"
    EXTENSIONS = "extensions"
    FAVORITES = "favorites"
    FLAGS = "flags"
    HEIGHT = "height"
    INVENTORY = "inventory"
    PARSERS = "parsers"
    QUERY = "query"
    RECORDS = "records"
    UI = "ui"
    WIDTH = "width"
    WRITE_EVERY = "write_every"
